name: mobile_assessment
description: Irecharge mobile team assessment

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.2
  dio: 5.1.2
  equatable: 2.0.5
  phosphor_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.1.2
  mocktail: ^1.0.0
  bloc_test: ^9.1.4

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
